### ISSUE TITLE
Cannot Run on MacOS or Raspbian

### ISSUE THREAD

**Issue by TheJostler** [Mobile-IoT-Security-Lab/Obfuscapk#4]
### Prerequisites

Before opening this issue, I tried the following steps:

* [ ] Installed the tool in a way [described in the readme](https://github.com/ClaudiuGeorgiu/Obfuscapk#-installation) and ran `python3 -m obfuscapk.cli --help` without any errors

* [ ] Ran the tool using: `python3 -m obfuscapk.cli -o Rebuild -o NewAlignment -o NewSignature <YOUR_APP.APK>` to verify that the app is not using anti-repackaging techniques

* [ ] Ran the tool using `--ignore-libs` flag to exclude third party libraries from the obfuscation

* [ x] Checked [FAQ](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/docs/FAQ.md) and [troubleshooting](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/docs/TROUBLESHOOTING.md)

* [ x] Checked for [existing similar issues on GitHub](https://github.com/issues?utf8=✓&q=is%3Aissue+repo%3AClaudiuGeorgiu/Obfuscapk)

### Description

I have followed each step exactally to install obfuscapk on both MacOS and Raspberry Pi and each time I get the same error when I try to run `python3 -m obfuscapk.cli --help`

### Steps to reproduce

1. Clone the repo, and follow all installation steps
2. `python3 -m obfuscapk.cli --help`

**Expected behavior:**

That the scripts should run normally

**Actual behavior:**

What actually happens is I get this output from python:

`$ python3 -m obfuscapk.cli --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/me/obfuscapk/src/obfuscapk/cli.py", line 189, in <module>
    main()
  File "/Users/me/obfuscapk/src/obfuscapk/cli.py", line 140, in main
    check_external_tool_dependencies()
  File "/Users/me/obfuscapk/src/obfuscapk/main.py", line 42, in check_external_tool_dependencies
    BundleDecompiler()
  File "/Users/me/obfuscapk/src/obfuscapk/toolbundledecompiler.py", line 31, in __init__
    if not os.path.isfile(full_bundledecompiler_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 30, in isfile
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType`

```
paste here the complete error message, including the command that generated the error
```

### Versions

* **Installation mode** (e.g., from source or with Docker): Source
* **Obufscapk version** (e.g., commit 0676488): Commit 9cc37b9
* **OS** (e.g., Ubuntu 16.04): Darwin 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; /RELEASE_X86_64 x86_64
* **Python version** (e.g., 3.7.4): 3.11.1
* **Apktool version** (e.g., v2.4.0): 2.9.3

I get the exact same error on both MacOS and Raspberry Pi

**Comment by lucaverderame** [comment]
Closed due to inactivity
